spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mes_hm_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 단계라 update 사용 (Member 테이블 변경사항 반영용)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8111

# JWT Secret Key (HS512 알고리즘을 위해 64바이트 이상 길이 필수)
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  expiration: 1800000 # 30분 (Access Token)
  refresh-token-validity-in-seconds: 604800 # 7일 (Refresh Token)
